/**
 * Runtime environment + integration readiness for the KLAIM backend.
 *
 * Every value is read INSIDE a function (never at module scope) because the
 * Worker runtime injects env per request.
 *
 * Integration status is derived from configuration only — KLAIM never reports
 * an integration as "live" unless the credentials required to reach the real
 * external service are actually present.
 */

export type IntegrationState = "live" | "pending_credentials" | "not_configured";

export interface IntegrationStatus {
  id: "digilocker" | "x402" | "algorand" | "goplausible" | "provider_agent" | "zk" | "mcp";
  label: string;
  state: IntegrationState;
  /** What is missing, in plain language, when not live. */
  detail: string;
  /** Env var names an operator must set to make this integration live. */
  requires: string[];
}

export function env(name: string): string | undefined {
  const value = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process
    ?.env?.[name];
  return value?.trim() ? value.trim() : undefined;
}

function has(...names: string[]): boolean {
  return names.every((n) => Boolean(env(n)));
}

export const DIGILOCKER_ENV = [
  "DIGILOCKER_CLIENT_ID",
  "DIGILOCKER_CLIENT_SECRET",
  "DIGILOCKER_REDIRECT_URI",
] as const;

export const X402_ENV = ["PROVIDER_WALLET_ADDRESS"] as const;
export const STRANDS_ENV = ["STRANDS_MODEL_ID"] as const;
export const ZK_ENV = ["MIDNIGHT_PROVER_URL"] as const;

/**
 * Shared secret for server-to-server calls from the KLAIM API (Danish's
 * backend) into this protocol service — e.g. POST /api/payments/settle. This
 * is NOT a wallet key and NOT an agent key; it only authenticates the trusted
 * backend caller. Never logged, never returned in a response.
 */
export function internalServiceToken(): string | undefined {
  return env("INTERNAL_SERVICE_TOKEN");
}

export function internalAuthConfigured(): boolean {
  return Boolean(internalServiceToken());
}

/**
 * Authenticate a server-to-server request by its `Authorization: Bearer`
 * header against INTERNAL_SERVICE_TOKEN. Returns false when the token is
 * unset (fail closed) or does not match.
 */
export function isInternalServiceRequest(request: Request): boolean {
  const expected = internalServiceToken();
  if (!expected) return false; // fail closed: no token configured → deny
  const authorization = request.headers.get("Authorization");
  const provided = authorization?.toLowerCase().startsWith("bearer ")
    ? authorization.slice(7).trim()
    : null;
  if (!provided || provided.length !== expected.length) return false;
  // Length-guarded equality; tokens are high-entropy so timing is not the
  // primary threat, but avoid an early-exit compare where cheap.
  let mismatch = 0;
  for (let i = 0; i < expected.length; i++) {
    mismatch |= expected.charCodeAt(i) ^ provided.charCodeAt(i);
  }
  return mismatch === 0;
}

export function digilockerConfigured(): boolean {
  return has(...DIGILOCKER_ENV);
}

export function x402Configured(): boolean {
  return has(...X402_ENV);
}

export function zkConfigured(): boolean {
  return has(...ZK_ENV);
}

export function strandsConfiguredEnv(): boolean {
  return has(...STRANDS_ENV);
}

export function integrationStatuses(): IntegrationStatus[] {
  const paid = x402Configured();
  return [
    {
      id: "mcp",
      label: "KLAIM MCP Server",
      state: "live",
      detail: "Real MCP endpoint served by this app.",
      requires: [],
    },
    {
      id: "x402",
      label: "x402 payments",
      state: paid ? "live" : "not_configured",
      detail: paid
        ? "402 challenges are generated by @x402/core + @x402/avm and settled through GoPlausible."
        : "PROVIDER_WALLET_ADDRESS is not set — the endpoint answers X402_NOT_CONFIGURED and no verification runs.",
      requires: [...X402_ENV],
    },
    {
      id: "algorand",
      label: "Algorand Testnet settlement",
      state: paid ? "live" : "not_configured",
      detail: paid
        ? "Settlement receipts carry real Algorand Testnet transaction ids, linked to Lora."
        : "No transaction ids are produced until the provider wallet is configured. KLAIM never fabricates a txId.",
      requires: [...X402_ENV],
    },
    {
      id: "goplausible",
      label: "GoPlausible facilitator",
      state: paid ? "live" : "not_configured",
      detail: paid
        ? "Payments are verified and settled by the GoPlausible x402 facilitator."
        : "Facilitator reachable, but no provider wallet is configured to receive payment.",
      requires: [...X402_ENV],
    },
    {
      id: "provider_agent",
      label: "Strands provider agent",
      state: "live",
      detail: strandsConfiguredEnv()
        ? "Strands agent orchestrates KLAIM's verification tools behind the payment boundary."
        : "Provider agent tools run deterministically (runtime=deterministic). Set STRANDS_MODEL_ID for the Strands runtime.",
      requires: [...STRANDS_ENV],
    },
    {
      id: "digilocker",
      label: "DigiLocker",
      state: digilockerConfigured() ? "live" : "pending_credentials",
      detail: digilockerConfigured()
        ? "Official DigiLocker OAuth 2.0 authorization + issued-document API."
        : "Adapter implemented. Awaiting official DigiLocker partner credentials.",
      requires: [...DIGILOCKER_ENV],
    },
    {
      id: "zk",
      label: "Zero-knowledge proofs (Midnight)",
      state: zkConfigured() ? "live" : "pending_credentials",
      detail: zkConfigured()
        ? "Proofs are generated by the configured Midnight prover."
        : "zkpService runs the local proof adapter. Proof objects are labelled engine=local until Midnight is connected.",
      requires: [...ZK_ENV],
    },
  ];
}
